apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: vllm-cluster
spec:
  type: NodePort
  selector:
    app: vllm-head
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # Set a custom node port, or leave blank for auto-assignment

